export type order = {
    _id: string;
    userId: string;
    productId: {
        _id: string;
        productName: string;
        description: string;
        image: string;
        price: number;
        material: string;
        branch: string;
        color: string;
        gender: string;
        size: string;
        quantityInStock: number;
        quantitySold: number;
        type: string;
        deleted: boolean;
        createdAt: string;
        updatedAt: string;
        __v: number;
        status: string;
    };
    status: string;
    totalAmount: number;
    paymentStatus: string;
    deleted: boolean;
    createdAt: string;
    updatedAt: string;
    __v: number;
};
